<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PackAsTool>false</PackAsTool>
        <IsPackable>true</IsPackable>
        <TemplateVisible>true</TemplateVisible>
        <TemplateName>NoonNewProject</TemplateName>
        <TemplateDescription>This template used for Noon co. new projects</TemplateDescription>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" Version="4.0.2" />
        <PackageReference Include="FirebaseAdmin" Version="3.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Entities\Entities.csproj" />
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>