<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HR_PMAC_BACK.Application\HR_PMAC_BACK.Application.csproj" />
    <ProjectReference Include="..\HR_PMAC_BACK.Infrastructure\HR_PMAC_BACK.Infrastructure.csproj" />
  </ItemGroup>

</Project>
