using Domain.Interfaces;

namespace Infrastructure.Repositories;

public class RepositoryManager(DapperContext context) : IRepositoryManager
{
    private readonly Lazy<IUserRepository> _userRepository = new(() => new UserRepository(context));
    private readonly Lazy<IEmployeeRepository> _employeeRepository = new(() => new EmployeeRepository(context));
    private readonly Lazy<IDirectorateRepository> _directorateRepository = new(() => new DirectorateRepository(context));
    private readonly Lazy<IDepartmentRepository> _departmentRepository = new(() => new DepartmentRepository(context));
    private readonly Lazy<ISectionRepository> _sectionRepository = new(() => new SectionRepository(context));
    private readonly Lazy<IPositionRepository> _positionRepository = new(() => new PositionRepository(context));
    private readonly Lazy<IJobTitleRepository> _jobTitleRepository = new(() => new JobTitleRepository(context));
    private readonly Lazy<IRankRepository> _rankRepository = new(() => new RankRepository(context));
    private readonly Lazy<IStoreEmployeeRepository> _storeEmployeeRepository = new(() => new StoreEmployeeRepository(context));
    private readonly Lazy<IGradeRepository> _gradeRepository = new(() => new GradeRepository(context));
    private readonly Lazy<IStepRepository> _stepRepository = new(() => new StepRepository(context));
    private readonly Lazy<IServiceContinuationRepository> _serviceContinuationRepository = new(() => new ServiceContinuationRepository(context));
    private readonly Lazy<IWorkCareerTypeRepository> _workCareerTypeRepository = new(() => new WorkCareerTypeRepository(context));
    private readonly Lazy<ICommingFromRepository> _commingFromRepository = new(() => new CommingFromRepository(context));
    private readonly Lazy<IFingerPrintExceptionTypeRepository> _fingerPrintExceptionTypeRepository = new(() => new FingerPrintExceptionTypeRepository(context));
    private readonly Lazy<ICareerRepository> _careerRepository = new(() => new CareerRepository(context));
    private readonly Lazy<IBasicSalaryRepository> _basicSalaryRepository = new(() => new BasicSalaryRepository(context));
    private readonly Lazy<IRaiseTypeRepository> _raiseTypeRepository = new(() => new RaiseTypeRepository(context));
    private readonly Lazy<IRaiseRepository> _raiseRepository = new(() => new RaiseRepository(context));
    private readonly Lazy<IVacationRepository> _vacationRepository = new(() => new VacationRepository(context));
    private readonly Lazy<IVacationTypeRepository> _vacationTypeRepository = new(() => new VacationTypeRepository(context));
    private readonly Lazy<IVacationTotalRepository> _vacationTotalRepository = new(() => new VacationTotalRepository(context));
    private readonly Lazy<ITrainingCourseRepository> _trainingCourseRepository = new(() => new TrainingCourseRepository(context));
    private readonly Lazy<IUniversityRepository> _universityRepository = new(() => new UniversityRepository(context));
    private readonly Lazy<IAdministrativeActionRepository> _administrativeActionRepository = new(() => new AdministrativeActionRepository(context));
    private readonly Lazy<IAdministrativeActionTypeRepository> _administrativeActionTypeRepository = new(() => new AdministrativeActionTypeRepository(context));
    private readonly Lazy<IRewardRepository> _rewardRepository = new(() => new RewardRepository(context));
    private readonly Lazy<ICommitteeRepository> _committeeRepository = new(() => new CommitteeRepository(context));
    private readonly Lazy<IDeligationRepository> _deligationRepository = new(() => new DeligationRepository(context));
    private readonly Lazy<IOfficialDocumentRepository> _officialDocumentRepository = new(() => new OfficialDocumentRepository(context));
    private readonly Lazy<IOfficialDocumentTypeRepository> _officialDocumentTypeRepository = new(() => new OfficialDocumentTypeRepository(context));
    private readonly Lazy<ICertificateRepository> _certificateRepository = new(() => new CertificateRepository(context));
    private readonly Lazy<IEducationCertificateRepository> _educationCertificateRepository = new(() => new EducationCertificateRepository(context));
    private readonly Lazy<ICertificatePublisherRepository> _certificatePublisherRepository = new(() => new CertificatePublisherRepository(context));
    private readonly Lazy<IPersonalCardRepository> _personalCardRepository = new(() => new PersonalCardRepository(context));
    private readonly Lazy<IMaritalStatusRepository> _maritalStatusRepository = new(() => new MaritalStatusRepository(context));
    private readonly Lazy<IServiceTypeRepository> _serviceTypeRepository = new(() => new ServiceTypeRepository(context));
    private readonly Lazy<ITaskStatusRepository> _taskStatusRepository = new(() => new TaskStatusRepository(context));
    private readonly Lazy<ILogFileRepository> _logFileRepository = new(() => new LogFileRepository(context));
    private readonly Lazy<IAddedServiceRepository> _addedServiceRepository = new(() => new AddedServiceRepository(context));
    private readonly Lazy<IConsultantTaskRepository> _consultantTaskRepository = new(() => new ConsultantTaskRepository(context));

    public IUserRepository User => _userRepository.Value;
    public IEmployeeRepository Employee => _employeeRepository.Value;
    public IDirectorateRepository Directorate => _directorateRepository.Value;
    public IDepartmentRepository Department => _departmentRepository.Value;
    public ISectionRepository Section => _sectionRepository.Value;
    public IPositionRepository Position => _positionRepository.Value;
    public IJobTitleRepository JobTitle => _jobTitleRepository.Value;
    public IRankRepository Rank => _rankRepository.Value;
    public IStoreEmployeeRepository StoreEmployee => _storeEmployeeRepository.Value;
    public IGradeRepository Grade => _gradeRepository.Value;
    public IStepRepository Step => _stepRepository.Value;
    public IServiceContinuationRepository ServiceContinuation => _serviceContinuationRepository.Value;
    public IWorkCareerTypeRepository WorkCareerType => _workCareerTypeRepository.Value;
    public ICommingFromRepository CommingFrom => _commingFromRepository.Value;
    public IFingerPrintExceptionTypeRepository FingerPrintExceptionType => _fingerPrintExceptionTypeRepository.Value;
    public ICareerRepository Career => _careerRepository.Value;
    public IBasicSalaryRepository BasicSalary => _basicSalaryRepository.Value;
    public IRaiseTypeRepository RaiseType => _raiseTypeRepository.Value;
    public IRaiseRepository Raise => _raiseRepository.Value;
    public IVacationRepository Vacation => _vacationRepository.Value;
    public IVacationTypeRepository VacationType => _vacationTypeRepository.Value;
    public IVacationTotalRepository VacationTotal => _vacationTotalRepository.Value;
    public ITrainingCourseRepository TrainingCourse => _trainingCourseRepository.Value;
    public IUniversityRepository University => _universityRepository.Value;
    public IAdministrativeActionRepository AdministrativeAction => _administrativeActionRepository.Value;
    public IAdministrativeActionTypeRepository AdministrativeActionType => _administrativeActionTypeRepository.Value;
    public IRewardRepository Reward => _rewardRepository.Value;
    public ICommitteeRepository Committee => _committeeRepository.Value;
    public IDeligationRepository Deligation => _deligationRepository.Value;
    public IOfficialDocumentRepository OfficialDocument => _officialDocumentRepository.Value;
    public IOfficialDocumentTypeRepository OfficialDocumentType => _officialDocumentTypeRepository.Value;
    public ICertificateRepository Certificate => _certificateRepository.Value;
    public IEducationCertificateRepository EducationCertificate => _educationCertificateRepository.Value;
    public ICertificatePublisherRepository CertificatePublisher => _certificatePublisherRepository.Value;
    public IPersonalCardRepository PersonalCard => _personalCardRepository.Value;
    public IMaritalStatusRepository MaritalStatus => _maritalStatusRepository.Value;
    public IServiceTypeRepository ServiceType => _serviceTypeRepository.Value;
    public ITaskStatusRepository TaskStatus => _taskStatusRepository.Value;
    public ILogFileRepository LogFile => _logFileRepository.Value;
    public IAddedServiceRepository AddedService => _addedServiceRepository.Value;
    public IConsultantTaskRepository ConsultantTask => _consultantTaskRepository.Value;
}
