using AutoMapper;
using Domain.Interfaces;
using Application.Interfaces;

namespace Application.Services;

public class ServiceManager(IRepositoryManager repositoryManager, IMapper mapper) : IServiceManager
{
    private readonly Lazy<IUserService> _userService = new(() => new UserService(repositoryManager, mapper));
    private readonly Lazy<IEmployeeService> _employeeService = new(() => new EmployeeService(repositoryManager, mapper));
    private readonly Lazy<IDirectorateService> _directorateService = new(() => new DirectorateService(repositoryManager, mapper));
    private readonly Lazy<IDepartmentService> _departmentService = new(() => new DepartmentService(repositoryManager, mapper));
    private readonly Lazy<ISectionService> _sectionService = new(() => new SectionService(repositoryManager, mapper));
    private readonly Lazy<IPositionService> _positionService = new(() => new PositionService(repositoryManager, mapper));
    private readonly Lazy<IJobTitleService> _jobTitleService = new(() => new JobTitleService(repositoryManager, mapper));
    private readonly Lazy<IRankService> _rankService = new(() => new RankService(repositoryManager, mapper));
    private readonly Lazy<IStoreEmployeeService> _storeEmployeeService = new(() => new StoreEmployeeService(repositoryManager, mapper));
    private readonly Lazy<IGradeService> _gradeService = new(() => new GradeService(repositoryManager, mapper));
    private readonly Lazy<IStepService> _stepService = new(() => new StepService(repositoryManager, mapper));
    private readonly Lazy<IServiceContinuationService> _serviceContinuationService = new(() => new ServiceContinuationService(repositoryManager, mapper));
    private readonly Lazy<IWorkCareerTypeService> _workCareerTypeService = new(() => new WorkCareerTypeService(repositoryManager, mapper));
    private readonly Lazy<ICommingFromService> _commingFromService = new(() => new CommingFromService(repositoryManager, mapper));
    private readonly Lazy<IFingerPrintExceptionTypeService> _fingerPrintExceptionTypeService = new(() => new FingerPrintExceptionTypeService(repositoryManager, mapper));
    private readonly Lazy<ICareerService> _careerService = new(() => new CareerService(repositoryManager, mapper));
    private readonly Lazy<IBasicSalaryService> _basicSalaryService = new(() => new BasicSalaryService(repositoryManager, mapper));
    private readonly Lazy<IRaiseTypeService> _raiseTypeService = new(() => new RaiseTypeService(repositoryManager, mapper));
    private readonly Lazy<IRaiseService> _raiseService = new(() => new RaiseService(repositoryManager, mapper));
    private readonly Lazy<IVacationService> _vacationService = new(() => new VacationService(repositoryManager, mapper));
    private readonly Lazy<IVacationTypeService> _vacationTypeService = new(() => new VacationTypeService(repositoryManager, mapper));
    private readonly Lazy<IVacationTotalService> _vacationTotalService = new(() => new VacationTotalService(repositoryManager, mapper));
    private readonly Lazy<ITrainingCourseService> _trainingCourseService = new(() => new TrainingCourseService(repositoryManager, mapper));
    private readonly Lazy<IUniversityService> _universityService = new(() => new UniversityService(repositoryManager, mapper));
    private readonly Lazy<IAdministrativeActionService> _administrativeActionService = new(() => new AdministrativeActionService(repositoryManager, mapper));
    private readonly Lazy<IAdministrativeActionTypeService> _administrativeActionTypeService = new(() => new AdministrativeActionTypeService(repositoryManager, mapper));
    private readonly Lazy<IRewardService> _rewardService = new(() => new RewardService(repositoryManager, mapper));
    private readonly Lazy<ICommitteeService> _committeeService = new(() => new CommitteeService(repositoryManager, mapper));
    private readonly Lazy<IDeligationService> _deligationService = new(() => new DeligationService(repositoryManager, mapper));
    private readonly Lazy<IOfficialDocumentService> _officialDocumentService = new(() => new OfficialDocumentService(repositoryManager, mapper));
    private readonly Lazy<IOfficialDocumentTypeService> _officialDocumentTypeService = new(() => new OfficialDocumentTypeService(repositoryManager, mapper));
    private readonly Lazy<ICertificateService> _certificateService = new(() => new CertificateService(repositoryManager, mapper));
    private readonly Lazy<IEducationCertificateService> _educationCertificateService = new(() => new EducationCertificateService(repositoryManager, mapper));
    private readonly Lazy<ICertificatePublisherService> _certificatePublisherService = new(() => new CertificatePublisherService(repositoryManager, mapper));
    private readonly Lazy<IPersonalCardService> _personalCardService = new(() => new PersonalCardService(repositoryManager, mapper));
    private readonly Lazy<IMaritalStatusService> _maritalStatusService = new(() => new MaritalStatusService(repositoryManager, mapper));
    private readonly Lazy<IServiceTypeService> _serviceTypeService = new(() => new ServiceTypeService(repositoryManager, mapper));
    private readonly Lazy<ITaskStatusService> _taskStatusService = new(() => new TaskStatusService(repositoryManager, mapper));
    private readonly Lazy<ILogFileService> _logFileService = new(() => new LogFileService(repositoryManager, mapper));
    private readonly Lazy<IAddedServiceService> _addedServiceService = new(() => new AddedServiceService(repositoryManager, mapper));
    private readonly Lazy<IConsultantTaskService> _consultantTaskService = new(() => new ConsultantTaskService(repositoryManager, mapper));

    public IUserService UserService => _userService.Value;
    public IEmployeeService EmployeeService => _employeeService.Value;
    public IDirectorateService DirectorateService => _directorateService.Value;
    public IDepartmentService DepartmentService => _departmentService.Value;
    public ISectionService SectionService => _sectionService.Value;
    public IPositionService PositionService => _positionService.Value;
    public IJobTitleService JobTitleService => _jobTitleService.Value;
    public IRankService RankService => _rankService.Value;
    public IStoreEmployeeService StoreEmployeeService => _storeEmployeeService.Value;
    public IGradeService GradeService => _gradeService.Value;
    public IStepService StepService => _stepService.Value;
    public IServiceContinuationService ServiceContinuationService => _serviceContinuationService.Value;
    public IWorkCareerTypeService WorkCareerTypeService => _workCareerTypeService.Value;
    public ICommingFromService CommingFromService => _commingFromService.Value;
    public IFingerPrintExceptionTypeService FingerPrintExceptionTypeService => _fingerPrintExceptionTypeService.Value;
    public ICareerService CareerService => _careerService.Value;
    public IBasicSalaryService BasicSalaryService => _basicSalaryService.Value;
    public IRaiseTypeService RaiseTypeService => _raiseTypeService.Value;
    public IRaiseService RaiseService => _raiseService.Value;
    public IVacationService VacationService => _vacationService.Value;
    public IVacationTypeService VacationTypeService => _vacationTypeService.Value;
    public IVacationTotalService VacationTotalService => _vacationTotalService.Value;
    public ITrainingCourseService TrainingCourseService => _trainingCourseService.Value;
    public IUniversityService UniversityService => _universityService.Value;
    public IAdministrativeActionService AdministrativeActionService => _administrativeActionService.Value;
    public IAdministrativeActionTypeService AdministrativeActionTypeService => _administrativeActionTypeService.Value;
    public IRewardService RewardService => _rewardService.Value;
    public ICommitteeService CommitteeService => _committeeService.Value;
    public IDeligationService DeligationService => _deligationService.Value;
    public IOfficialDocumentService OfficialDocumentService => _officialDocumentService.Value;
    public IOfficialDocumentTypeService OfficialDocumentTypeService => _officialDocumentTypeService.Value;
    public ICertificateService CertificateService => _certificateService.Value;
    public IEducationCertificateService EducationCertificateService => _educationCertificateService.Value;
    public ICertificatePublisherService CertificatePublisherService => _certificatePublisherService.Value;
    public IPersonalCardService PersonalCardService => _personalCardService.Value;
    public IMaritalStatusService MaritalStatusService => _maritalStatusService.Value;
    public IServiceTypeService ServiceTypeService => _serviceTypeService.Value;
    public ITaskStatusService TaskStatusService => _taskStatusService.Value;
    public ILogFileService LogFileService => _logFileService.Value;
    public IAddedServiceService AddedServiceService => _addedServiceService.Value;
    public IConsultantTaskService ConsultantTaskService => _consultantTaskService.Value;
}